
/*Even Fibonacci numbers
 *Problem 2 
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * Luke D. Young
 * May 11th, 2017
 * 
 */
public class Problem2 {
	static int problemSize;
	static int sum;
	static int previous;
	static int minus2;

	@SuppressWarnings("resource")
	public static void main(String[] args){
		System.out.println("Input Top number to calculate sum:");
		problemSize = 4000000;
		System.out.println("You entered: " + problemSize);
		
		//call calculation
		sum = 2;
		sum = findSum(problemSize);
		
		// return sum
		System.out.println("The sum of all even integers from 1-" + problemSize 
				+ " in the Fibonacci sequence is: " + sum);
	}
	 public static int findSum(int count){
		 minus2 = 1;
		 previous = 2;
		 for(int i = 3; i < count; i = minus2 + previous){
			 minus2 = previous;
			 previous = i;
			 if(i%2 == 0){ //if even
				 sum = sum + i;
			 }
			
			System.out.println("Previous = " + previous);
		 }
		 return sum;
	 }

}
